<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="49510" started-at="2020-07-05T12:05:26Z" finished-at="2020-07-05T12:06:15Z">
    <groups>
    </groups>
    <test name="Test Case One" duration-ms="25107" started-at="2020-07-05T12:05:26Z" finished-at="2020-07-05T12:05:51Z">
      <class name="testCases.TC_001">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testCases.TC_001@69b0fd6f]" name="launchBrowser" is-config="true" duration-ms="12303" started-at="2020-07-05T12:05:26Z" finished-at="2020-07-05T12:05:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="testCase001(java.lang.String, java.lang.String)[pri:0, instance:testCases.TC_001@69b0fd6f]" name="testCase001" duration-ms="11991" started-at="2020-07-05T12:05:38Z" data-provider="getData" finished-at="2020-07-05T12:05:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CASUAL DRESSES]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Product successfully added to your shopping cart]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [Product successfully added to your shopping cart]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [Product successfully added to your shopping cart]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testCases.TC_001.testCase001(TC_001.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase001 -->
        <test-method status="PASS" signature="quitBrowser()[pri:0, instance:testCases.TC_001@69b0fd6f]" name="quitBrowser" is-config="true" duration-ms="752" started-at="2020-07-05T12:05:50Z" finished-at="2020-07-05T12:05:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- testCases.TC_001 -->
    </test> <!-- Test Case One -->
    <test name="Test Case Two" duration-ms="11915" started-at="2020-07-05T12:05:51Z" finished-at="2020-07-05T12:06:03Z">
      <class name="testCases.TC_002">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:testCases.TC_002@2a70a3d8]" name="startBrowser" is-config="true" duration-ms="11215" started-at="2020-07-05T12:05:51Z" finished-at="2020-07-05T12:06:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="PASS" signature="testTitle()[pri:0, instance:testCases.TC_002@2a70a3d8]" name="testTitle" duration-ms="10" started-at="2020-07-05T12:06:03Z" finished-at="2020-07-05T12:06:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTitle -->
        <test-method status="PASS" signature="quiteBrowser()[pri:0, instance:testCases.TC_002@2a70a3d8]" name="quiteBrowser" is-config="true" duration-ms="688" started-at="2020-07-05T12:06:03Z" finished-at="2020-07-05T12:06:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quiteBrowser -->
      </class> <!-- testCases.TC_002 -->
    </test> <!-- Test Case Two -->
    <test name="Test Case Three" duration-ms="11980" started-at="2020-07-05T12:06:03Z" finished-at="2020-07-05T12:06:15Z">
      <class name="testCases.TC_003">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:testCases.TC_003@396e2f39]" name="startBrowser" is-config="true" duration-ms="11305" started-at="2020-07-05T12:06:03Z" finished-at="2020-07-05T12:06:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="FAIL" signature="testTitle()[pri:0, instance:testCases.TC_003@396e2f39]" name="testTitle" duration-ms="11" started-at="2020-07-05T12:06:15Z" finished-at="2020-07-05T12:06:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Store..] but found [My Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Store..] but found [My Store]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testCases.TC_003.testTitle(TC_003.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTitle -->
        <test-method status="PASS" signature="quiteBrowser()[pri:0, instance:testCases.TC_003@396e2f39]" name="quiteBrowser" is-config="true" duration-ms="660" started-at="2020-07-05T12:06:15Z" finished-at="2020-07-05T12:06:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quiteBrowser -->
      </class> <!-- testCases.TC_003 -->
    </test> <!-- Test Case Three -->
  </suite> <!-- Suite -->
</testng-results>
